### ISSUE TITLE
May want to try the benchmark with 0.26.0:

### ISSUE THREAD

**Issue by bd82** [christianvoigt/argdown-parser#1]
There are many breaking changes.
https://github.com/SAP/chevrotain/issues/423#issuecomment-289225219

But the performance characteristics of the basic Tokens (now there is just one type of Tokens...)
have drastically improved.

On my simple JSON benchmark The simple Tokens with **full** (not lazy) position information achieve 
About 90% of the performance of the previous "SimpleLazyTokens". And you can also disable
the full position information tracking to get about 100% of the performance of the removed
"SimpleLazyTokens".

**Comment by christianvoigt** [comment]
that sounds great! I definitely will update my Chevrotain parser soon. But for a fair comparison I would also have to put considerable effort into updating the ANTLR4 parser. Currently I do not know if I will find the time for this. For example I still have not gotten a satisfying answer to [this stackoverflow question](http://stackoverflow.com/questions/42874346/how-to-implement-lookbehind-and-lookahead-for-lexing-bold-and-italic-text-ranges) and it really takes time in ANTLR4 to figure everything out for yourself.

**Comment by bd82** [comment]
> Currently I do not know if I will find the time for this.

Thats fine, there is limited time and prioritization must be performed...

> that sounds great! I definitely will update my Chevrotain parser soon.

Keep in mind the breaking changes to the custom patterns.
https://github.com/SAP/chevrotain/issues/380#issuecomment-287629918

matches are **no** longer from the **start of the text** which you often use (**^**) in your parser.

I'm working on even more lexer optimizations and improvements so the APIs
could still be a little unstable 😄.
